<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="smartcar">

    <xacro:property name="wheelbase_length" value="0.257"/>
    <xacro:property name="wheelbase_width" value="0.17"/>
    <xacro:property name="chassis" value="0.0125"/>
    <xacro:property name="wheel_diameter" value="0.064"/>
    <xacro:property name="wheel_radius" value="${wheel_diameter / 2}"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_orientation" value="${90 * (pi / 180)}"/>
                          

    <material name="body_material">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="wheel_material">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="imu_material">
        <color rgba="1 1 0 1"/>
    </material>

    <material name="lidar_material">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="footprint_material">
        <color rgba="0 1 1 0.1"/>
    </material>

    <xacro:macro name="front_wheel" params="prefix parent x y z wheel_offset">
        <joint name="front_${prefix}_wheel_steer_joint" type="revolute">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="front_${prefix}_wheel_steer_link"/>
            <axis xyz="0 0 1"/>
            <limit lower="-${45 * (pi / 180)}" upper="${45 * (pi / 180)}" effort="10" velocity="1"/>
        </joint>

        <link name="front_${prefix}_wheel_steer_link">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <visual>
                <geometry>
                    <box size="0.01 0.01 0.01"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </visual>

            <collision>
                <geometry>
                    <box size="0.01 0.01 0.01"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>

            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.00005" ixy="0.0" ixz="0.0" iyy="0.00005" iyz="0.0" izz="0.00005"/>
            </inertial>
        </link>

        <gazebo reference="front_${prefix}_wheel_steer_link">
            <material>Gazebo/Red</material>
        </gazebo>

        <joint name="front_${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="front_${prefix}_wheel_steer_link"/>
            <child link="front_${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="front_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_orientation} 0 0"/>
                <material name="wheel_material"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_orientation} 0 0"/>
            </collision>

            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
            </inertial>
        </link>

        <gazebo reference="front_${prefix}_wheel_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="back_wheel" params="prefix parent x y z wheel_offset">
        <joint name="back_${prefix}_wheel_joint" type="continuous">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="back_${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="back_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_orientation} 0 0"/>
                <material name="wheel_material"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 ${wheel_offset} 0" rpy="${wheel_orientation} 0 0"/>
            </collision>

            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
            </inertial>
        </link>

        <gazebo reference="back_${prefix}_wheel_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <link name="base_link">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_to_chassis" type="fixed">
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${wheelbase_length} ${wheelbase_width} ${chassis}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="body_material"/>
        </visual>
        <collision>
            <geometry>
                <box size="${wheelbase_length} ${wheelbase_width} ${chassis}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <!-- <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/> -->
            <inertia ixx="0.0121" ixy="0.0" ixz="0.0" iyy="0.0276" iyz="0.0" izz="0.0396"/>
        </inertial>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0.0001" rpy="0 0 0" />
            <geometry>
                <box size="${wheelbase_length} ${wheelbase_width} 0"/>
            </geometry>
            <material name="footprint_material"/>
        </visual>
    </link>

    <gazebo reference="base_footprint">
        <material>Gazebo/TurquoiseGlow</material>
    </gazebo>

    <xacro:front_wheel prefix="left" parent="base_link" x="${wheelbase_length / 2}" y="${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="${wheel_width / 2}"/>
    <xacro:front_wheel prefix="right" parent="base_link" x="${wheelbase_length / 2}" y="-${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="-${wheel_width / 2}"/>
    
    <xacro:back_wheel prefix="left" parent="base_link" x="-${wheelbase_length / 2}" y="${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="${wheel_width / 2}"/>
    <xacro:back_wheel prefix="right" parent="base_link" x="-${wheelbase_length / 2}" y="-${wheelbase_width / 2}" z="${wheel_radius}" wheel_offset="-${wheel_width / 2}"/>


    <xacro:property name="imu_size" value="0.01"/>
    <xacro:property name="lidar_size" value="0.025"/>

    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
            <material name="imu_material"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
        </inertial>
    </link>

    <gazebo reference="imu_link">
        <sensor name="my_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <plugin name="my_imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                    <remapping>~/out:=imu_data</remapping>
                </ros>
            </plugin>
        </sensor>
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="base_to_imu" type="fixed">
        <origin xyz="0 0 ${wheel_diameter}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <link name="sllidar_base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${lidar_size}" radius="${lidar_size}"/>
            </geometry>
            <material name="lidar_material"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${lidar_size}" radius="${lidar_size}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.2"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
        </inertial>
    </link>

    <gazebo reference="sllidar_base_link">
        <sensor name="sensor_gpu_ray" type="ray">
            <visualize>true</visualize>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1.0</resolution>
                        <min_angle>-${pi}</min_angle>
                        <max_angle>${pi}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.5</min>
                    <max>50.0</max>
                </range>
            </ray>
            <always_on>true</always_on>
    
            <plugin name="laser_scan_plugin" filename="libgazebo_ros_ray_sensor.so">
                <output_type>sensor_msgs/LaserScan</output_type>
                <frameName>sllidar_base_link</frameName> 
                <topicName>/scan</topicName> 
                <remapping>~/out:=scan</remapping> 
                <robotNamespace>/</robotNamespace> 
                <updateRate>30.0</updateRate> 
            </plugin>
        </sensor>

        <material>Gazebo/Purple</material>
    </gazebo>

    <joint name="base_to_lidar" type="fixed">
        <origin xyz="${wheelbase_length / 2} 0 ${wheel_diameter * 1.5}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="sllidar_base_link"/>
    </joint>

    <gazebo>
        <plugin name="car_gazebo_plugin" filename="libcar_gazebo_plugin.so"></plugin>
    </gazebo>
</robot>
